In [25]:
# for macOS 10.12.6 issue - urllib and “SSL: CERTIFICATE_VERIFY_FAILED” Error
# solution: https://stackoverflow.com/a/28052583/2670476
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import pandas as pd
import yaml

In [2]:
config_file = open('config.yaml')
config = yaml.load(config_file, Loader=yaml.FullLoader)

In [3]:
# review_colname = 'content'
review_colname = config['review_colname']

df = pd.read_csv('csv_output/3_blablacar/blablacar-carpooling-and-bus_de_apple_appstore_review.csv', usecols=review_colname)
df

                                                 review
0     Die App ist generell prima und übersichtlich. ...
1     Grundsätzlich bin ich froh über BlaBlaCar, wei...
2     Wie im Titel bereits erwähnt, haben sich die S...
3     Ich habe mich vor dem Update für paar Sachen r...
4     Ganz ehrlich, ich bin extrem begeistert. Vor e...
...                                                 ...
7175  Mehr braucht man nicht.Suche ist einfach und ü...
7176  Blablacar an sich ist prima. Allerdings ist di...
7177  Ab dem 26.11 wird die Konkurrenz kostenpflicht...
7178  Tolle App, einfach zu handhaben und eine echte...
7179  Alternative zu Mitfahrgelegenheiten.de. Die Ap...

[7180 rows x 1 columns]

In [4]:
df.to_excel('xls_output/test.xlsx')

In [34]:
df = pd.read_excel('xls_output/test_en_translation.xlsx')

In [35]:
df

,Unnamed: 0,review,Unnamed: 2,Unnamed: 3
0,0,The app is generally great and clear. I have a...,NaN,NaN
1,NaN,- Sometimes the app gets stuck when you want t...,NaN,NaN
2,NaN,- better suggestions for meeting points along ...,NaN,NaN
3,NaN,- I wanted to take two people with me and I to...,NaN,NaN
4,NaN,- Can I rate passengers who cancel at very sho...,NaN,NaN
...,...,...,...,...
12673,NaN,NaN,NaN,NaN
12674,NaN,NaN,NaN,NaN
12675,NaN,NaN,NaN,NaN
12676,Text-to-speech function is limited to 200 char...,NaN,NaN,NaN
12677,NaN,NaN,Options : History : Feedback : Donate,Close